services:

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: interview_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    image: vkrishnan1999/auth-service:latest
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/interview_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  student-service:
    image: vkrishnan1999/student-service:latest
    container_name: student-service
    ports:
      - "8083:8083"

  question-service:
    image: vkrishnan1999/question-service:latest
    container_name: question-service
    ports:
      - "8082:8082"

  quiz-service:
    image: vkrishnan1999/quiz-service:latest
    container_name: quiz-service
    ports:
      - "8084:8084"

  api-gateway:
    image: vkrishnan1999/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"

volumes:
  postgres_data: